# This file is automatically generated and committed to Github 'flux-infra' by this terraform:
#   https://github.com/narvar/terraform-aws-accounts/blob/main/dev/dev71/40-eks1-bootstrap/30-flux-config-map.tf
#
# Don't edit it by hand in the 'flux-infra' repo.


# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: narvar-system
generatorOptions:
 disableNameSuffixHash: true
 labels:
   kustomize.generated.resource: "flux"
 annotations:
   reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
   reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

configMapGenerator:
  - name: flux-generated-terraform-values
    # White spaces are significant: do not put white spaces before or after the equal sign ("=").
    literals:
      - aws_region=${aws_region}
      # - aws_nats={aws_nats}
      # - aws_private_subnets={aws_private_subnets}
      # - aws_public_subnets={aws_public_subnets}
      - route53_public_hosted_zone1_id=${route53_public_hosted_zone1_id}
      - route53_public_hosted_zone1_domain_name_list=${route53_public_hosted_zone1_domain_name_list}
      # - irsa_atlantis_role_arn={irsa_atlantis_role_arn}
      - irsa_cert_manager_role_arn=${irsa_cert_manager_role_arn}
      - irsa_cluster_autoscaler_role_arn=${irsa_cluster_autoscaler_role_arn}
      - irsa_external_dns_role_arn=${irsa_external_dns_role_arn}
      - irsa_external_secrets_role_arn=${irsa_external_secrets_role_arn}
      - eks_cluster_name=${eks_cluster_name}
      # - eks_cluster_version={eks_cluster_version}
