#################################################################################################################
# For inline comments that apply to all accounts' terraform, see the *.tf files in 'devops' account (OU='admin').
# All common comments belong there.
# Only the comments that are unique to this particular account should be in this file.
#################################################################################################################

locals {
  aws_auth_append = var.aws_auth_append
}

resource "github_repository_file" "aws-auth" {
  repository          = "flux-infra"
  branch              = "master"
  file                = var.aws_auth_file
  commit_message      = var.github_repository_file_cm_commit_message
  commit_author       = "Narvar terraform user from Github repo terraform-aws-accounts"
  commit_email        = "terraform@narvar.com"
  overwrite_on_create = true

  content = <<EOT
# This file is automatically generated and committed to Github 'flux-infra' by this terraform:
#   https://github.com/narvar/terraform-aws-accounts/blob/main/qa/qa71/40-eks1-bootstrap/30-flux-config-map-aws-auth.tf
#
# Don't edit it by hand in the 'flux-infra' repo.

${data.terraform_remote_state.eks.outputs.aws_auth_configmap_yaml}
${local.aws_auth_append}
EOT
}
