---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict, -c=.yamllint]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
        verbose: true
      - id: terraform_docs
        verbose: true
      - id: terraform_tfsec
        verbose: true

  - repo: git@github.com:narvar/precommit-hooks.git
    rev: v0.2.0
    hooks:
      - id: terrascan
        verbose: true
