# An example of ClusterConfig object specifying subnets for a nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster1
  region: us-west-2



vpc:
  id: "vpc-4f164c37"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-west-2a:
        id: "subnet-042b9f7c"
        cidr: "172.31.16.0/20" # (optional, must match CIDR used by the given subnet)
      us-west-2b:
        id: "subnet-95fb2adf"
        cidr: "172.31.32.0/20"
      us-west-2c:
        id: "subnet-a19711fc"
        cidr: "172.31.0.0/20"
      us-west-2d:
        id: "subnet-3a1e2011"
        cidr: "172.31.48.0/20"



managedNodeGroups:
  - name: ng-1-web
    labels: { role: web  }
    instanceType: t3.medium
    desiredCapacity: 4
    securityGroups:
      attachIDs: ["sg-0ce199be55ec0f0a3", "sg-09bd020f280f958b6"]
    volumeSize: 10
    ssh:
      publicKeyName: tester2
      allow: true
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
    tags:
      nodegroup-role: web
    subnets:
      - us-west-2a
      - us-west-2b
      - us-west-2c
      - us-west-2d
