apiVersion: v1
kind: Service
metadata:
  name: my-image-canary
  labels:
    app: my-image-canary
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: my-image-canary
