apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image-canary-v-1-1
spec:
  selector:
    matchLabels:
      app: my-image-canary
  replicas: 1 
  template:
    metadata:
      labels:
        app: my-image-canary
        track: canary
    spec:
      containers:
        - name: my-image-canary-v-1-1
          image: chauwei150/my-image:1.1      
          ports:
            - containerPort: 80
