# An example of ClusterConfig object specifying subnets for a nodegroup
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-west-2

vpc:
  id: vpc-013036a85371a5e5e
  cidr: "10.10.0.0/16"
  subnets:
    public:
      public-one:
        id: subnet-0afdf1d595b6c24dc
        cidr: 10.10.31.0/24
        # az: us-west-2a # any unambiguous combination of these is allowed
      public-two:
        id: subnet-013b3340cb71c04f1
        cidr: 10.10.32.0/24
      public-three:
        id: subnet-064e6a5ce17452f9e
        cidr: 10.10.33.0/24

managedNodeGroups:
  - name: ng-1-web
    labels: { role: web  }
    instanceType: t3.medium
    desiredCapacity: 3
    securityGroups:
      attachIDs: ["sg-092ab83fd554762eb", "sg-099aae67d84a801ab"]
    volumeSize: 10
    ssh:
      publicKeyName: charles
      allow: false
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
    tags:
      nodegroup-role: web
    subnets:
      - public-one
      - public-two
      - public-three
